version: '3'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextwbc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: